"""change bool

Revision ID: 59f90d2925fa
Revises: 695b9ece9741
Create Date: 2024-07-10 18:46:55.552321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f90d2925fa'
down_revision = '695b9ece9741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('availability_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('availability_status',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
