"""second migration

Revision ID: 6bbf1448693c
Revises: bfae3a5c86e0
Create Date: 2024-07-10 12:16:26.254985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbf1448693c'
down_revision = 'bfae3a5c86e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_carowner',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_carowner',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
